language: cpp
sudo: required
dist: trusty

notifications:
    email: false

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler: clang
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang

before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then ./.ci/gtest.sh; fi
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install clang-format; fi
script:
    - make
    - if [ $TRAVIS_OS_NAME == osx ]; then make lint; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then make test; fi
